Repository Subhradeep10/Fitnezz, pull requests merged in 2022-09, with the labels that each got.

#244 Social icons
  home.css
  index.html
Labels: intermediate, SSOC, ready to merge

#248 Sign-Up Page has been Added
  joinin.html
  signup.html
  signup_style.css
Labels: intermediate, SSOC, ready to merge

#251 Fix navbar
  about.css
  about.html
  contact.css
  contact.html
  images/about1.jpg
  images/about2.jpg
  images/about3.jpg
  images/home.jpg
  join.css
  joinin.html
Labels: SSOC, beginner, ready to merge

#249 about section created
  about.css
  about.html
  images/about1.jpg
  images/about2.jpg
  images/about3.jpg
  images/home.jpg
Labels: intermediate, SSOC, ready to merge

#253 Added Margin to the title of the cards in Featured Classes
  home.css
Labels: SSOC, beginner, ready to merge

#255 Added more cards in the "Meet the Trainers" section
  images/trainer1.jpg
  images/trainer2.jpg
  images/trainer3.jpg
  images/trainer4.jpg
  images/trainer5.jpg
  index.html
Labels: SSOC, beginner, ready to merge

#267 Update issue#258 done
  index.html
Labels: SSOC, beginner, ready to merge

#240 Tricept
  index.css
  tricepWorkout.html
Labels: SSOC, beginner, ready to merge

#269 Added scroll back to top button
  home.css
  index.html
Labels: intermediate, SSOC, ready to merge

#277 Fixed Issues :- #275, #276
  about.css
  about.html
  contact.css
  contact.html
  videos/gym-video.mp4
Labels: intermediate, SSOC, ready to merge

#279 Added margin-bottom to Buttons in Scheduled Class Section
  home.css
Labels: SSOC, beginner, ready to merge

#282 Added relevant text in the "About" section
  about.html
Labels: SSOC, beginner, ready to merge

#239 Link Color
  home.css
Labels: SSOC, beginner, ready to merge

#293 Increasing the spacing in Chest Workout page
  chestworkout.html
Labels: SSOC, beginner, ready to merge

#303 Cardio Page has been added
  cardio.html
  images/air hand.gif
  images/jog.gif
  images/jumping jacks.gif
  images/junp.gif
  index.css
  index.html
Labels: intermediate, SSOC, ready to merge

#307 Add files via upload
  index.html
Labels: SSOC, beginner, ready to merge

#310 fixed icons
  index.html
Labels: SSOC, beginner, ready to merge

#311 Contact page UI glitch fix and improvement
  contact.css
Labels: SSOC, beginner, ready to merge

#313 about us page made responsive
  about.css
Labels: SSOC, beginner, ready to merge

#318 Increasing the spacing in Arm Workout Page
  armworkout.html
Labels: assigned, SSOC, beginner

#321 To Update the UI(Issue #317)
  index.css
  index.html
Labels: SSOC, beginner, ready to merge

#314 Contacts
  contact.css
  contact.html
Labels: intermediate, SSOC, ready to merge
